### ISSUE TITLE
Verify that site contact form works and who reads info@cellproject.net

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/cellproject#22]
Site have a contact form: https://cellproject.net/contact we should make sure it works. We should also check and verify that the right people get info@cellproject.net. As it sits now is the site not able to send username password resets or from the contact form.

## Technical changes.

Configure site to either use NIRD SMTP proxy or deliver directly at cellproject.net mail exchange server (MX) at bluehost.

**Comment by steinmb** [comment]
@deheckman are you able to do some footwork on the mail address?

**Comment by deheckman** [comment]
I've just sent queries to both the email address and the form.

**Comment by deheckman** [comment]
I have not heard anything from either.  I had assumed that such queries would go to me or to Greg.  But is there any way to find out where they are going?

**Comment by steinmb** [comment]
The mail exchange server (MX) point to bluehost. In other words the mail should end up there. Perhaps Greg can help you out getting access. I have no access to bluehost cellnetwork admin bit though I should prob. been given one.

Once we have a working mail/mail-list I'll can dig into altering/changing the cellnetwork.net config making the contact form work.

**Comment by deheckman** [comment]
I have contacted Greg to see see if he can help you gain access.  I cc'ed you on that email.

**Comment by steinmb** [comment]
Configured site to use `smarthost.uninett.no` SMTP server. Tested contact form and it work as expected.
