### ISSUE TITLE
Aggregated content is missing for ELMCIP and is not working for po-ex and iloveepoetry.org

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/cellproject#27]
In "News from Partners" section of the site front page we show aggregated content (imported) from partner sites.
https://cellproject.net/news_from_partners 

## problem

* [x] https://po-ex.net import is not working.
* [x] http://iloveepoetry.org is not working.
* [x] ELMCIP is missing.

**Comment by steinmb** [comment]
I think the reason that ELMCIP is missing is that there was no RSS feed to import from at the site news page. During the https://elmcip.net/news redesign I created a feed that CELL can use. Added the elmcip feed and imported content, looks OK.

![Screenshot 2020-12-17 at 11 53 10](https://user-images.githubusercontent.com/683617/102478916-7e008980-405e-11eb-826c-8d53e62504f5.png)

**Comment by steinmb** [comment]
PO-EX feed is there but it is not working. I the link is wrong. Replaced it with https://po-ex.net/feed/ that works but are we pulling in the right type of content?

@deheckman - Have a look at https://cellproject.net/aggregator/sources/3 do you think this is what we are suppose to pull in? I struggle with the language but it is coming from https://po-ex.net/noticias/

**Comment by steinmb** [comment]
Change the RSS link for iloveepoetry to http://iloveepoetry.org/?feed=rss2 - Seem to be working on force import.

![Screenshot 2020-12-17 at 12 11 46](https://user-images.githubusercontent.com/683617/102480808-1bf55380-4061-11eb-98dd-599a528dfe36.png)

@deheckman the feed is at https://cellproject.net/aggregator/sources/2 I think is the right content.

**Comment by steinmb** [comment]
Bumping this issue. I would love to get this verified so we can go ahead and close it. @deheckman any questions about what I need your help to?

**Comment by deheckman** [comment]
I will have to check with Rui about the "feed."  My recollection is that po.ex has different kinds of content and they wish to be selective about what is pushed into CELL.

**Comment by steinmb** [comment]
Got the right feed URL from Rui Torres. Removed old post from incorrect feed URL and re-imported. Consider issue fixed, closing.

```
https://po-ex.net/category/news/
https://po-ex.net/category/news/feed/

Rui Torres
Professor Associado com Agregação
Faculdade de Ciências Humanas e Sociais
Universidade Fernando Pessoa - Portugal
```
