### ISSUE TITLE
Remove Drupal core search from cellproject

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/cellproject#29]
CELL uses Solr to store the search index, even so it still have the "out of the box" search module from Drupal turned on. 

![Screenshot 2021-01-07 at 12 03 56](https://user-images.githubusercontent.com/683617/103886986-a2daa080-50e2-11eb-8522-8e6e81e35bb5.png)

This make no sense. We spend time indexing a search engine that no one know where are since we are no places linking to it pluss the official Solr duplicate all content.

## Problems

After disable and uninstall we see two warnings in the logs:

```
Notice: Undefined index: search_block_form in drupal_retrieve_form() 
(line 809 of drupal/includes/form.inc).

Warning: call_user_func_array() expects parameter 1 to be a valid callback, 
function 'search_block_form' not found or invalid function name in drupal_retrieve_form() 
(line 844 of drupal/includes/form.inc).
```

## Suggested fix

* [x] Disable and uninstall Drupal search module (https://cellproject.net/search)
* [ ] Retest site. Make sure no warning are coming from theme/preprocessing/old-config.

## How to test

Nothing to test.

**Comment by steinmb** [comment]
@deheckman any objections?

**Comment by deheckman** [comment]
So are you saying there are two different search tools operating?  We only need the general SOLR search and then the option of the faceted search for more targeted queries.  So, simplicity, I think is better.  I am fine with this fix!

**Comment by steinmb** [comment]
Yes, there is two completely different search running - https://www.drupal.org/docs/7/core/modules/search/overview

I have now disabled core search in production though I should retest the site. There might be places in the site that expect a search block to exist though It is never used. Nothing breaks though I would create warnings and noise in our system logs.

**Comment by steinmb** [comment]
I noticed a couple of warnings in the logs. I updated the issue to reflect this to make sure we address this before closing.

**Comment by steinmb** [comment]
@deheckman - Tracked the error down. Should be running without warnings and notices in log on every page load. That is a lot of entries. This will pushed to the production sit on next release.

commit smbjorklund/centum@d97b35cc3155fc5226c53523855979d90f1a4474 (HEAD -> master, origin/master, origin/HEAD)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Fri Jan 8 12:19:18 2021 +0100

    Issue 29 template_preprocess_page try to load non existing search block

    Causes warnings and notices all our logs if core search
    is disabled.

**Comment by deheckman** [comment]
Great!
