### ISSUE TITLE
Verify that Google Analytics works

### ISSUE THREAD

**Issue by steinmb** [smbjorklund/cellproject#30]
CELL track all visitors with Google analytics https://marketingplatform.google.com/about/analytics/

## Scope

* We need to verify that tracking works. 
* Verify that only the one that needs access to the data have it.
* Since we track there should also be a [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) statement on the site.

## Suggested solution

* Create new tracking property on same account as ELMCIP.
* Add Davin as a user to property.

**Comment by deheckman** [comment]
Stein, do I need to create a google analytics account to access this?

**Comment by steinmb** [comment]
Account(s) that have access to this should exist, data is logged to a existing tracking ID. You could try and as ask prev. CELL personnel if they have access. If one of them have admin/edit access they can add your google account to it. https://support.google.com/analytics/answer/1009694?hl=en&authuser=0

If no one have access to it we have two options:

1. Remove tracking. Do we really need this traffic information? If no one have had access for years I sort of doubt it. We then do not need to worry about GDPR since we do no longer track users.
1. Create new tracking account and ID, update the site DNS and finally change the tracking id used by cellnetwork.net.

**Comment by deheckman** [comment]
I think option 2 is better.  We don't have the data, haven't been using it, and the site has largely been dormant.

**Comment by steinmb** [comment]
Have created a new tracking property on the same account ELMCIP uses and added Davin to it as a user. We have to let it run for a few hours before confirming that tracking data is collected. By default do also Scott have access.

**Comment by steinmb** [comment]
I confirm we are getting data.

![Screenshot 2021-01-18 at 10 53 52](https://user-images.githubusercontent.com/683617/104899730-7f81e200-597b-11eb-81c7-34591a549ed0.png)

@deheckman going to keep this open until you confirm that you are able to login and get to the data.

**Comment by steinmb** [comment]
>@deheckman going to keep this open until you confirm that you are able to login and get to the data.

Can you confirm that you found the statistic. If so, I can go ahead and close this issue.

**Comment by steinmb** [comment]
No feedback. Closing as fixed
